# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f39a12cef9ea4844666c5cff3efb47c216c7d3c2b6852485a0b524bb27b44e95492cd9d3f4d644f5c58a05ff7cbd5cf35033f19a9eccbb66dce5327697605b9a

test:
  secret_key_base: 135524f52d6823398572a741767c5da8fe17a8b7df54ffa0c9f26c89633531a2ddca66f64fe3305e7fed1b2bc48a9747238f95682081516eb381049dde3c75cb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
